'use client';

import { LegalLayout } from '@/components/legal/legal-layout';
import Link from 'next/link';

const sections = [
  { id: 'acceptance', title: '1. Acceptance of Terms' },
  { id: 'service', title: '2. Description of Service' },
  { id: 'accounts', title: '3. User Accounts' },
  { id: 'use-policy', title: '4. Acceptable Use' },
  { id: 'disclaimer', title: '5. AI Recommendations Disclaimer' },
  { id: 'affiliate', title: '6. Affiliate Disclosure' },
  { id: 'ip', title: '7. Intellectual Property' },
  { id: 'billing', title: '8. Subscriptions & Billing' },
  { id: 'liability', title: '9. Limitation of Liability' },
  { id: 'governing-law', title: '10. Governing Law' },
  { id: 'disputes', title: '11. Dispute Resolution' },
];

export default function TermsAndConditions() {
  return (
    <LegalLayout
      title="Terms & Conditions"
      lastUpdated="June 20, 2025"
      sections={sections}
      relatedLink={{ href: '/privacy-policy', label: 'Privacy Policy' }}
    >
      <div className="prose prose-invert prose-gold max-w-none">
        <section id="acceptance" className="scroll-mt-32">
          <h2 className="text-4xl font-headline text-primary mb-6">1. Acceptance of Terms</h2>
          <p className="text-lg leading-relaxed text-foreground/80">
            By accessing or using DRAPE AI, you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree to all of these terms, do not use the service.
          </p>
        </section>

        <section id="service" className="scroll-mt-32">
          <h2 className="text-4xl font-headline text-primary mb-6">2. Description of Service</h2>
          <p className="text-lg leading-relaxed text-foreground/80">
            DRAPE AI is a technology-driven fashion styling platform that uses artificial intelligence to analyze user photos and data to provide outfit recommendations. Our services include silhouette analysis, skin tone mapping, and marketplace price tracking.
          </p>
        </section>

        <section id="accounts" className="scroll-mt-32">
          <h2 className="text-4xl font-headline text-primary mb-6">3. User Accounts</h2>
          <p className="text-lg leading-relaxed text-foreground/80 mb-4">
            To use certain features, you must register for an account. By registering, you agree that:
          </p>
          <ul className="space-y-2 text-foreground/70">
            <li>• You are at least 13 years of age.</li>
            <li>• The information provided during registration is accurate and complete.</li>
            <li>• You will maintain the security of your password and account details.</li>
            <li>• You are solely responsible for all activity that occurs under your account.</li>
          </ul>
        </section>

        <section id="disclaimer" className="scroll-mt-32">
          <h2 className="text-4xl font-headline text-primary mb-6">5. AI Recommendations Disclaimer</h2>
          <div className="bg-accent/10 p-8 rounded-2xl border border-accent/20 border-l-4 border-l-accent">
            <h4 className="font-headline text-2xl text-accent mb-4">Nature of Suggestions</h4>
            <p className="text-lg leading-relaxed text-foreground/80">
              Outfit suggestions provided by DRAPE AI are generated by artificial intelligence models based on your input. While we strive for accuracy, these are subjective styling recommendations. DRAPE AI does not guarantee satisfaction with any purchases made based on these suggestions.
            </p>
            <p className="mt-4 text-sm text-foreground/60 italic">
              Note: Prices and inventory levels are fetched in real-time but can change rapidly. Always verify the final details on the merchant's platform.
            </p>
          </div>
        </section>

        <section id="affiliate" className="scroll-mt-32">
          <h2 className="text-4xl font-headline text-primary mb-6">6. Affiliate Disclosure</h2>
          <p className="text-lg leading-relaxed text-foreground/80">
            DRAPE AI participates in affiliate marketing programs with platforms like Amazon India, Flipkart, and Meesho. This means we may earn a small commission on qualifying purchases made through our links, at no additional cost to you. Our styling recommendations are based purely on style-fit logic and are not influenced by commission rates.
          </p>
        </section>

        <section id="ip" className="scroll-mt-32">
          <h2 className="text-4xl font-headline text-primary mb-6">7. Intellectual Property</h2>
          <p className="text-lg leading-relaxed text-foreground/80">
            The DRAPE AI name, logo, design system, and proprietary algorithms are the sole property of DRAPE AI. User-uploaded photos remain the property of the user. Style suggestions generated by the AI are provided for your personal, non-commercial use only.
          </p>
        </section>

        <section id="billing" className="scroll-mt-32">
          <h2 className="text-4xl font-headline text-primary mb-6">8. Subscriptions & Billing</h2>
          <p className="text-lg leading-relaxed text-foreground/80 mb-4">
            Premium features are billed on a recurring monthly or annual basis via Razorpay.
          </p>
          <ul className="space-y-2 text-foreground/70">
            <li>• Subscriptions can be cancelled at any time from your account settings.</li>
            <li>• We do not provide refunds for partial months or unused credits.</li>
            <li>• Price changes will be notified at least 30 days in advance.</li>
          </ul>
        </section>

        <section id="governing-law" className="scroll-mt-32">
          <h2 className="text-4xl font-headline text-primary mb-6">10. Governing Law</h2>
          <p className="text-lg leading-relaxed text-foreground/80">
            These terms shall be governed by and construed in accordance with the laws of India. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts in Bangalore, Karnataka.
          </p>
        </section>

        <section id="disputes" className="scroll-mt-32">
          <h2 className="text-4xl font-headline text-primary mb-6">11. Dispute Resolution</h2>
          <p className="text-lg leading-relaxed text-foreground/80">
            If you have a dispute, we encourage you to contact our legal team at <span className="text-primary underline">legal@drapeai.in</span> first. We will attempt to resolve any issues through informal negotiation within 60 days.
          </p>
        </section>
      </div>
    </LegalLayout>
  );
}
