'use client';

import { LegalPageLayout } from '@/components/legal/legal-page-layout';

const sections = [
  { id: 'general', title: 'General Information' },
  { id: 'ai', title: 'AI Limitations' },
  { id: 'third-party', title: 'Third-Party Products' },
  { id: 'pricing', title: 'Price Accuracy' },
  { id: 'affiliate', title: 'Affiliate Disclosure' },
];

export default function DisclaimerPage() {
  return (
    <LegalPageLayout
      title="Legal Disclaimer"
      lastUpdated="January 1, 2025"
      readTime="3 min"
      sections={sections}
    >
      <section id="general" className="scroll-mt-32">
        <h2 className="text-3xl font-headline text-gold mb-6">General Information</h2>
        <p className="text-foreground/70 leading-relaxed">
          DRAPE AI provides fashion recommendations for informational purposes only. The content provided through our AI systems and human curation is not professional styling, fashion, or retail advice. Decisions made based on our recommendations are at your own discretion.
        </p>
      </section>

      <section id="ai" className="scroll-mt-32 mt-12">
        <h2 className="text-3xl font-headline text-gold mb-6">AI Limitations</h2>
        <p className="text-foreground/70 leading-relaxed">
          Our AI recommendations are generated by automated systems and may not account for all individual factors such as specific fabric sensitivities, lighting variations, or micro-measurement nuances. Results are heavily dependent on the quality of user input and uploaded photography.
        </p>
      </section>

      <section id="third-party" className="scroll-mt-32 mt-12">
        <h2 className="text-3xl font-headline text-gold mb-6">Third-Party Products</h2>
        <p className="text-foreground/70 leading-relaxed">
          DRAPE AI is a curation platform, not a retailer. We are not responsible for product quality, authenticity, delivery, returns, or customer service handled by Amazon, Flipkart, or Meesho. Please verify all product specifications on the retailer's platform before committing to a purchase.
        </p>
      </section>

      <section id="affiliate" className="scroll-mt-32 mt-12">
        <h2 className="text-3xl font-headline text-gold mb-6">Affiliate Disclosure</h2>
        <p className="text-foreground/70 leading-relaxed">
          We participate in affiliate marketing programs with major Indian retailers. This means we may earn a commission on qualifying purchases made through our links. This comes at no additional cost to you and helps maintain the high-order rendering engines of the DRAPE AI atelier.
        </p>
      </section>
    </LegalPageLayout>
  );
}